services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: mysql-database
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-p123"]
      interval: 10s
      retries: 5
      start_period: 30s   # If 30s doesn't work, increase to 60s
      timeout: 5s

  flask-app:
    image: umerleghari01/flask-app:v1
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DB: mysql-database
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:
networks:
  twotier:

