name: My Workflow
on:
  push:
    branches:
      - master
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  show-repository-files:
    runs-on: ubuntu-latest
    steps:
      - name: Show the files of the repository
        run: |
          echo "Repository:${{ github.repository }} contains the following files:"
          find .
